[build]
  publish = "."

[[redirects]]
  from = "https://www.moraremipanema.com/*"
  to = "https://moraremipanema.com/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=UTF-8"
    Cache-Control = "public, max-age=0, must-revalidate"
